name: help_care
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.2
  connectivity_plus: ^7.0.0
  fluttertoast: ^9.0.0

  carousel_slider: ^5.0.0
  google_fonts: ^8.0.1

  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.2
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  printing: ^5.13.4
  url_launcher: ^6.3.0
  path_provider: ^2.1.4
  share_plus: ^12.0.1
  pdf: ^3.11.0

  # ✅ local notifications + timezone (ใช้เวอร์ชันเดียว)
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0

  fl_chart: ^1.1.1
  audioplayers: ^6.5.1
  open_filex: ^4.5.0
  http: ^1.2.0

  # ✅ เพิ่มสำหรับระบบข่าวสาร
  xml: ^6.5.0
  webview_flutter: ^4.10.0
  html: ^0.15.4

  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  firebase_messaging: ^16.1.0
  flutter_screenutil: ^5.9.3
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/helpcare-OA.png"
  min_sdk_android: 28
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/helpcare-OA.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/
    - assets/audio/
