name: help_care
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.2
  connectivity_plus: ^7.0.0
  fluttertoast: ^9.0.0

  # ของเดิมที่มีอยู่แล้ว
  carousel_slider: ^5.0.0
  google_fonts: ^6.1.0

  # ชุด Firebase + ฟีเจอร์ที่เราใช้ในโปรเจกต์
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  printing: ^5.13.4
  url_launcher: ^6.3.0
  path_provider: ^2.1.4
  share_plus: ^12.0.1
  pdf: ^3.11.0
  flutter_local_notifications: ^19.5.0
  android_alarm_manager_plus: ^5.0.0
  timezone: ^0.10.1
  fl_chart: ^0.66.2
  audioplayers: ^5.2.1
  open_filex: ^4.5.0
  http: ^1.2.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.0.0
  geolocator: ^13.0.1
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/logohelpcare.png"
  min_sdk_android: 28
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/logohelpcare.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/
    - assets/audio/
